defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
sass:
  sass_dir: _sass/--foundation
exclude:
  - README.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - vendor
